language: node_js
node_js:
  - 0.10

# Make sure we have new NPM.
before_install:
  - npm install -g npm
  - npm config set loglevel warn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - rm -rf node_modules/karma
  - export $(openssl aes-256-cbc -pass env:CREDENTIALS_PASS -d -in credentials)

script:
  - grunt build test lint
  - ./scripts/integration-tests.sh
